name: Java Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy Java Application to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Step 1: Install OpenJDK 17 and wget
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo apt-get install -y wget

            # Step 2: Download and install Tomcat 9 (Updated URL)
            TOMCAT_VERSION="9.0.70"
            TOMCAT_URL="https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz"
            wget $TOMCAT_URL
            if [ $? -ne 0 ]; then
              echo "Tomcat download failed. Exiting."
              exit 1
            fi
            sudo tar -xvzf apache-tomcat-${TOMCAT_VERSION}.tar.gz -C /opt/
            sudo mv /opt/apache-tomcat-${TOMCAT_VERSION} /opt/tomcat
            sudo chmod +x /opt/tomcat/bin/*.sh
            sudo sh /opt/tomcat/bin/startup.sh

            # Step 3: Deploy the WAR file to Tomcat's webapps directory
            rm -rf /opt/tomcat/webapps/*
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} target/my-maven-webapp.war ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/tomcat/webapps/my-maven-webapp.war

            # Step 4: Restart Tomcat to deploy the application
            sudo sh /opt/tomcat/bin/shutdown.sh
            sudo sh /opt/tomcat/bin/startup.sh
