name: Java Web Application Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  deploy-java-webapp:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the GitHub Actions job
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml  # Clean and build the project

      - name: Add SSH private key to the agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy WAR file to the server's Tomcat webapps directory
        run: |
          scp -o StrictHostKeyChecking=no -P 22 target/*.war ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/tomcat/webapps/

      - name: Tomcat to deploy the WAR file
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Ensure OpenJDK 21 is installed
            sudo apt-get update
            sudo apt-get install -y openjdk-21-jdk wget
            # Tomcat to deploy the WAR file
            sudo systemctl daemon-reload
          EOF


