name: Java Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Add SSH private key to the agent
      - name: Add SSH private key to the agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Deploy the Java Application via SSH
      - name: Deploy Java Application via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Step 1: Install OpenJDK 17 and wget
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk wget


            # Step 3: Install Tomcat
            sudo chown -R $USER:$USER /opt/apache-tomcat-10.1.34/
            sudo chmod -R u+x /opt/apache-tomcat-10.1.34/bin

            # Step 4: Start Tomcat service
            sudo sh /opt/apache-tomcat-10.1.34/bin/startup.sh
            sudo systemctl daemon-reload
            sudo systemctl start apache-tomcat-10.1.34
            sudo systemctl enable apache-tomcat-10.1.34

            # Step 5: Allow Tomcat's default port (8080)
            sudo ufw allow 8080
            sudo ufw reload

            # Step 6: Deploy the WAR file to Tomcat's webapps directory
            rm -rf /opt/apache-tomcat-10.1.34/webapps/*
            cp /home/${USER}/workspace/my-maven-webapp/target/my-maven-webapp.war /opt/apache-tomcat-10.1.34/webapps/my-maven-webapp.war

            # Step 7: Restart Tomcat to deploy the application
            sudo sh /opt/apache-tomcat-10.1.34/bin/shutdown.sh
            sudo sh /opt/apache-tomcat-10.1.34/bin/startup.sh
          EOF
