name: Java Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java with Maven 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Java application using Maven
      - name: Build with Maven
        run: mvn clean install

      # Deploy Java Application using appleboy/ssh-action
      - name: Deploy Java Application to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/deploy && rm -rf *
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} target/*.jar ubuntu@13.51.156.222:**/*
            java -jar **/*.jar
