name: Java Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java with Maven 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Java application using Maven
      - name: Build with Maven
        run: mvn clean install

      # Deploy Java Application using appleboy/ssh-action
      - name: Deploy Java Application to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Install Tomcat on the server
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            sudo apt-get install -y wget
            wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz
            sudo tar -xvzf apache-tomcat-9.0.69.tar.gz -C /opt/
            sudo mv /opt/apache-tomcat-9.0.69 /opt/tomcat
            sudo chmod +x /opt/tomcat/bin/*.sh
            sudo sh /opt/tomcat/bin/startup.sh
            
            # Deploy WAR file to Tomcat's webapps directory
            rm -rf /opt/tomcat/webapps/*
            scp -i ${{ secrets.SSH_PRIVATE_KEY }} target/*.war ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/tomcat/webapps/index.jsp.war

            # Restart Tomcat (optional)
            sudo sh /opt/tomcat/bin/shutdown.sh
            sudo sh /opt/tomcat/bin/startup.sh
