name: Java Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-java:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Add SSH private key to the agent
      - name: Add SSH private key to the agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Deploy the Java Application via SSH
      - name: Deploy Java Application via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Step 1: Install OpenJDK 17 and wget
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk wget

          EOF
